################################################################################
# Test file of API HTTP Routes
# Requires REST Client extension for VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/api

### 404
GET {{ endpoint }}/clientsss

#########################
#       CLIENTS         #
#########################

### Get all clients and their addresses
GET {{ endpoint }}/clients

### Get a client and his addresses by an id that does not exist
GET {{ endpoint }}/clients/123

### Get a client and his addresses by id
GET {{ endpoint }}/clients/1

### Create client
POST {{ endpoint }}/clients
content-type: application/json

{
    "client": {
        "firstname": "Chuck",
        "lastname": "Norris",
        "email": "test@co.io",
        "phone": "0644588854",
        "provider_id": 1
    },
    "addresses": [
        {
        "number": "56bis",
        "street": "test",
        "postal_code": "56900",
        "city": "test"
        },
        {
        "number": "57bis",
        "street": "test",
        "postal_code": "56900",
        "city": "test"
        }
    ]
}

### Create an error client
POST {{ endpoint }}/clients
content-type: application/json

{
    "client": {
        "firstname": "Chuck",
        "lastname": "Norris",
        "email": "chuck.norris@gmail.com",
        "provider_id": 1
    },
    "addresses": [
        {
        "street": "test",
        "postal_code": "56900",
        "city": "test"
        }
    ]
}

### Update client
PATCH {{ endpoint }}/clients/2
content-type: application/json

{
    "client": {
        "firstname": "Jon",
        "email": "Jon@gmail.com"
    },
    "addresses": [
        {
        "id": 4,
        "number": "58bis"
        },
        {
        "id": 6,
        "number": "56bis",
        "postal_code": "56980"
        },
        {
        "id": null,
        "number": "58ter",
        "street": "testa",
        "postal_code": "56900",
        "city": "testa"
        }
    ]
}

### Delete client
DELETE {{ endpoint }}/clients/2

### Delete client address
DELETE {{ endpoint }}/clients/address/26
